/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackIcon: typeof import('./components/icons/BackIcon.vue')['default']
    ChatList: typeof import('./components/ChatList.vue')['default']
    ChatListItem: typeof import('./components/ChatListItem.vue')['default']
    ChatWindow: typeof import('./components/ChatWindow.vue')['default']
    MessageBubble: typeof import('./components/MessageBubble.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    MessengerLayout: typeof import('./components/MessengerLayout.vue')['default']
    OnlineIndicator: typeof import('./components/OnlineIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendIcon: typeof import('./components/icons/SendIcon.vue')['default']
  }
}
